server:
  port: 8000
spring:
  application:
    name: zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: false
    hostname: localhost
   
    
zuul:
  host:
    connect-timeout-millis: 160000
    socket-timeout-millis: 160000
  routes:
    demo:
      path: /getName
      service-id: demo
      strip-prefix: false
    report-service:
      path: /expenseClaim/**
      service-id: report-service
      strip-prefix: false  
    expense-service:
      path: /**
      service-id: expense-service
      strip-prefix: false
    google:
      path: /google/**
      url: https://www.google.com
      
  
  

ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 60000
  MaxTotalHttpConnections: 500
  MaxConnectionsPerHost: 100    

 

